services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    restart: "always"
  frontend:
    build:
      context: frontend
    ports:
      - "80:3000"
    links:
      - "backend"
    depends_on:
      - "backend"
    restart: "always"
